### ISSUE TITLE
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_dir before flags were parsed.

### ISSUE THREAD

**Issue by SnowRipple** [victorbonnet/waldo_finder_app#1]
Hey there!
        Great project! I am trying o make it work but I am hitting an error:
`:~/workspace/waldo_finder_app$ python tensorflow_models/research/object_detection/model_main.py     --pipeline_config_path=${PIPELINE_CONFIG_PATH}     --model_dir=/home/snowripple/workspace/waldo_finder_app     --num_train_steps=10     --num_eval_steps=1     --logtostderr/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
/usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/usr/local/lib/python2.7/dist-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
/usr/local/lib/python2.7/dist-packages/pandas/__init__.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas import hashtable, tslib, lib
/usr/local/lib/python2.7/dist-packages/pandas/__init__.py:25: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  from pandas import hashtable, tslib, lib
/usr/local/lib/python2.7/dist-packages/pandas/core/common.py:13: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas.algos as algos
/usr/local/lib/python2.7/dist-packages/pandas/core/common.py:13: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  import pandas.algos as algos
/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas.index as _index
/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py:9: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  import pandas.index as _index
/usr/local/lib/python2.7/dist-packages/pandas/tseries/index.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._period as period
/usr/local/lib/python2.7/dist-packages/pandas/tseries/index.py:36: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  import pandas._period as period
/usr/local/lib/python2.7/dist-packages/pandas/sparse/array.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._sparse import SparseIndex, BlockIndex, IntIndex
/usr/local/lib/python2.7/dist-packages/pandas/sparse/array.py:18: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  from pandas._sparse import SparseIndex, BlockIndex, IntIndex
/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas.parser as _parser
/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py:30: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  import pandas.parser as _parser
ERROR:root:Trying to access flag --model_dir before flags were parsed.
Traceback (most recent call last):
  File "tensorflow_models/research/object_detection/model_main.py", line 101, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow_models/research/object_detection/model_main.py", line 55, in main
    config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 488, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_dir before flags were parsed.`

Any idea what I am doing wrong? What python version are you using?

Many Thanks!

**Comment by SnowRipple** [comment]
Ok so I added
`if __name__ == '__main__':
  import sys
  from absl import flags
  FLAGS = flags.FLAGS
  FLAGS(sys.argv)
  tf.app.run()`

in model_main.py ans flags seem to be parsed ok now but  I am getting:

`tensorflow_models/research/object_detection/model_main.py:
  --checkpoint_dir: Path to directory holding a checkpoint.  If `checkpoint_dir`
    is provided, this binary operates in eval-only mode, writing resulting
    metrics to `model_dir`.
  --[no]eval_training_data: If training data should be evaluated for this job.
    (default: 'false')
  --hparams_overrides: Hyperparameter overrides, represented as a string
    containing comma-separated hparam_name=value pairs.
  --model_dir: Path to output model directory where event and checkpoint files
    will be written.
  --num_eval_steps: Number of train steps.
    (an integer)
  --num_train_steps: Number of train steps.
    (an integer)
  --pipeline_config_path: Path to pipeline config file.
  --[no]run_once: If running in eval-only mode, whether to run just one round of
    eval vs running continuously (default).
    (default: 'false')

absl.flags:
  --flagfile: Insert flag definitions from the given file into the command line.
    (default: '')
  --undefok: comma-separated list of flag names that it is okay to specify on
    the command line even if the program does not define a flag with that name.
    IMPORTANT: flags in this list that have arguments MUST use the --flag=value
    format.
    (default: '')
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7f845a42d578>) includes params argument, but params are not passed to Estimator.
2018-08-24 17:07:58.090055: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 1.38252 seconds (attempt 1 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:07:59.475967: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 1.39459 seconds (attempt 2 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:08:00.874110: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 2.28023 seconds (attempt 3 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:08:03.157646: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 4.98754 seconds (attempt 4 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:08:08.148023: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 8.76797 seconds (attempt 5 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:08:16.919085: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 16.7071 seconds (attempt 6 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:08:33.629101: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 32.5233 seconds (attempt 7 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:09:06.155570: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 32.0156 seconds (attempt 8 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
2018-08-24 17:09:38.173563: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 32.4834 seconds (attempt 9 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
`
It seems that it wants to connect me with the google cloud although I want to train it locally (I don't have google cloud account). Is it possible to train it locally?

**Comment by victorbonnet** [comment]
Hey, 

I am using python 2.7. I have just pushed the conda [environment](https://github.com/victorbonnet/waldo_finder_app/commit/986e42336976f0ecdbe81e3f4c9d9b76a2657aef) I am using for this project.

It's hard to tell what could be wrong with the stacktrace. 

The `model_dir` doesn't seem correct, except if you moved it. Shouldn't it be `/home/snowripple/workspace/waldo_finder_app/models/ssd_mobilenet_v2`?

**Comment by SnowRipple** [comment]
Hey @victorbonnet 

      Thanks for replying so fast! I have a problem with using your requirements.yml (I am new to conda, was using virtualenv before). Every time I am trying to recreate your environment with 'conda env create -f environment.yml' I get:
`
Solving environment: failed

ResolvePackageNotFound: 
  - jbig==2.1=h4d881f8_0
  - pluggy==0.6.0=py27had36429_0
  - pyaudio==0.2.7=py27h3777516_1
  - scikit-learn==0.19.1=py27h9788993_0
  - funcsigs==1.0.2=py27hb9f6266_0
  - glob2==0.6=py27h55c9705_0
  - alabaster==0.7.10=py27h9dd7d6e_0
  - pyyaml==3.12=py27ha7932d0_1
  - sip==4.19.8=py27h0a44026_0
  - docutils==0.14=py27h0befae3_0
  - h5py==2.7.1=py27ha8ecd60_2
  - nbconvert==5.3.1=py27h6455e4c_0
  - curl==7.60.0=ha441bb4_0
  - blaze==0.11.3=py27hb49378a_0
  - msgpack-python==0.5.6=py27h04f5b5a_0
  - click==6.7=py27h2b86a94_0
  - nose==1.3.7=py27h2ee3cb8_2
  - libcxxabi==4.0.1=hebd6815_0
  - bzip2==1.0.6=h1de35cc_5
  - ruamel_yaml==0.15.35=py27h1de35cc_1
  - unicodecsv==0.14.1=py27h170f95c_0
  - yaml==0.1.7=hc338f04_2
  - gevent==1.3.0=py27h1de35cc_0
  - jupyter_core==4.4.0=py27h5ea6ba4_0
  - cryptography==2.2.2=py27h1de35cc_0
  - qtawesome==0.4.4=py27hdeb2f59_0
  - blosc==1.14.3=hd9629dc_0
  - hdf5==1.10.2=hfa1e0ec_1
  - pywavelets==0.5.2=py27hd99e88a_0
  - cdecimal==2.3=py27h1de35cc_3
  - urllib3==1.22=py27hc3787e9_0
  - et_xmlfile==1.0.1=py27hc42f929_0
  - pycparser==2.18=py27h0d28d88_1
  - backports.shutil_get_terminal_size==1.0.0=py27hc9115de_2
  - clyent==1.2.2=py27hc0ae608_0
  - pyflakes==1.6.0=py27h4446e76_0
  - partd==0.3.8=py27h7560dbf_0
  - jsonschema==2.6.0=py27hd9b497e_0
  - scipy==1.1.0=py27hcaad992_0
  - get_terminal_size==1.0.0=h7520d66_0
  - cytoolz==0.9.0.1=py27h1de35cc_0
  - jinja2==2.10=py27h70b8dc5_0
  - ssl_match_hostname==3.5.0.1=py27h8780752_2
  - appscript==1.0.1=py27h451298e_1
  - qtconsole==4.3.1=py27hdc90b4f_0
  - boto==2.48.0=py27hacdd0fd_1
  - mkl-service==1.1.2=py27hcba3029_4
  - mpc==1.0.3=h7a72875_5
  - libedit==3.1.20170329=hb402a30_2
  - python==2.7.15=h138c1fe_0
  - pillow==5.1.0=py27hfcce615_0
  - bottleneck==1.2.1=py27h71f98a3_0
  - numexpr==2.6.5=py27h057f876_0
  - psutil==5.4.5=py27h1de35cc_0
  - zlib==1.2.11=hf3cbc9b_2
  - pickleshare==0.7.4=py27h37e3d41_0
  - libffi==3.2.1=h475c297_4
  - sphinxcontrib==1.0=py27hd2ed746_1
  - zeromq==4.2.5=h378b8a2_0
  - pycurl==7.43.0.1=py27hdbc3d79_0
  - libxslt==1.1.32=hb819dd2_0
  - prompt_toolkit==1.0.15=py27h4a7b9c2_0
  - statsmodels==0.9.0=py27h917ab60_0
  - openssl==1.0.2o=h26aff7b_0
  - llvmlite==0.23.1=py27hc454e04_0
  - lazy-object-proxy==1.3.1=py27h712ce3f_0
  - futures==3.2.0=py27h1b80678_0
  - libcxx==4.0.1=h579ed51_0
  - xlwt==1.2.0=py27hbeec4ae_0
  - mistune==0.8.3=py27h1de35cc_1
  - wrapt==1.10.11=py27hd341262_0
  - numpy-base==1.14.3=py27h7ef55bc_1
  - libgfortran==3.0.1=h93005f0_2
  - gmp==6.1.2=hb37e062_1
  - qt==5.9.5=h02808f3_0
  - glib==2.56.1=h35bc53a_0
  - pandoc==1.19.2.1=ha5e8f32_1
  - singledispatch==3.4.0.3=py27he22c18d_0
  - six==1.11.0=py27h7252ba3_1
  - jupyter_console==5.2.0=py27h9702a86_1
  - testpath==0.3.1=py27h72d81a5_0
  - pygments==2.2.0=py27h1a556bb_0
  - wcwidth==0.1.7=py27h817c265_0
  - itsdangerous==0.24=py27h3948ded_1
  - locket==0.2.0=py27ha10513d_1
  - anaconda-project==0.8.2=py27h2dc806c_0
  - mpfr==3.1.5=h711e7fd_2
  - sqlalchemy==1.2.7=py27hb402a30_0
  - webencodings==0.5.1=py27h19a9f58_1
  - requests==2.18.4=py27h9b2b37c_1
  - xz==5.2.4=h1de35cc_4
  - pyqt==5.9.2=py27h11d3b92_0
  - traitlets==4.3.2=py27hcf08151_0
  - scandir==1.7=py27h1de35cc_0
  - rope==0.10.7=py27hffa1879_0
  - zict==0.1.3=py27h5fff8b1_0
  - entrypoints==0.2.3=py27hd680fb1_2
  - chardet==3.0.4=py27h2842e91_1
  - ncurses==6.1=h0a44026_0
  - sphinxcontrib-websupport==1.0.1=py27h857890b_1
  - libcurl==7.60.0=hf30b1f0_0
  - functools32==3.2.3.2=py27h8ceab06_1
  - pytables==3.4.3=py27h5ca999c_2
  - jpeg==9b=he5867d9_2
  - ipython_genutils==0.2.0=py27h8b9a179_0
  - greenlet==0.4.13=py27h1de35cc_0
  - libssh2==1.8.0=h322a93b_4
  - readline==7.0=hc1231fa_4
  - pandas==0.23.0=py27h1702cab_0
  - enum34==1.1.6=py27hf475452_1
  - astropy==2.0.6=py27h917ab60_1
  - backports==1.0=py27hb4f9756_1
  - sqlite==3.23.1=hf1716c9_0
  - numpy==1.14.3=py27he6379a5_1
  - subprocess32==3.5.0=py27h1de35cc_0
  - scikit-image==0.13.1=py27h1de35cc_1
  - gettext==0.19.8.1=h15daf44_3
  - xlwings==0.11.8=py27_0
  - snappy==1.1.7=he62c110_3
  - cffi==1.11.5=py27h342bebf_0
  - appnope==0.1.0=py27hb466136_0
  - datashape==0.5.4=py27hd6a1745_0
  - libopenblas==0.2.20=hdc02c5d_4
  - mpmath==1.0.0=py27h6b0eff6_2
  - pyzmq==17.0.0=py27h1de35cc_1
  - expat==2.2.5=hb8e80ba_0
  - icu==58.2=h4b95b61_1
  - unixodbc==2.3.6=h3efe00b_0
  - cycler==0.10.0=py27hfc73c78_0
  - contextlib2==0.5.5=py27h9cb85f4_0
  - snowballstemmer==1.2.1=py27h68ac032_0
  - tblib==1.3.2=py27ha684fc4_0
  - python.app==2=py27hf2d5e94_7
  - kiwisolver==1.0.1=py27h9856860_0
  - xlrd==1.1.0=py27hbd41ed1_1
  - bkcharts==0.2=py27haafc882_0
  - idna==2.6=py27hedea723_1
  - freetype==2.8=h12048fb_1
  - pyparsing==2.2.0=py27h5bb6aaf_0
  - fastcache==1.0.2=py27h1de35cc_2
  - cython==0.28.2=py27h1de35cc_0
  - markupsafe==1.0=py27hd3c86fa_1
  - matplotlib==2.2.2=py27ha7267d0_0
  - libxml2==2.9.8=hab757c2_1
  - backports_abc==0.5=py27h6972548_0
  - numba==0.38.0=py27h1702cab_0
  - pandocfilters==1.4.2=py27hed78c4e_1
  - nbformat==4.4.0=py27hddc86d0_0
  - pycosat==0.6.3=py27h6c51c7e_0
  - mccabe==0.6.1=py27h1f69e8d_0
  - lzo==2.10=h362108e_2
  - libsodium==1.0.16=h3efe00b_0
  - libtiff==4.0.9=hcb84e12_1
  - sympy==1.1.1=py27hce55102_0
  - beautifulsoup4==4.6.0=py27h9416283_1
  - gmpy2==2.0.8=py27h4bc979a_2
  - bitarray==0.8.1=py27h1de35cc_1
  - pycrypto==2.6.1=py27h1de35cc_8
  - pcre==8.42=h378b8a2_0
  - odo==0.5.1=py27h992a9f7_0
  - lxml==4.2.1=py27h7166777_0
  - seaborn==0.8.1=py27h6bd0ddc_0
  - libpng==1.6.34=he12f830_0
  - configparser==3.5.0=py27hc7edf1b_0
  - dbus==1.13.2=h760590f_1
  - pyodbc==4.0.23=py27h0a44026_0
  - libiconv==1.15=hdd342a3_7
  - tk==8.6.7=h35a86e2_3
  - colorama==0.3.9=py27hbbe92b6_0
  - ptyprocess==0.5.2=py27h70f6364_0
`
I assumed that conda will install all requirements automatically, but it  does not seem like it, can you help?

**Comment by SnowRipple** [comment]
Is your environment based on MacOS? I work on Ubuntu, maybe builds are mismatching...

Edit: Removing build numbers in requirements.yml makes it work across-platforms

**Comment by victorbonnet** [comment]
I am on MacOS. My environment might not work on Linux :(

**Comment by SnowRipple** [comment]
ok, I think I'm getting closer... can you tell me which tensorflow version are you using please?

**Comment by victorbonnet** [comment]
Locally I have `1.7.1` installed. 

But I mostly played with Google Cloud ML. It seems that It uses `1.0` as default if we don'
t specify the runtime. Which I did not

**Comment by SnowRipple** [comment]
Many Thanks! Ok, I have it working but suprisingly I am hitting "ResourceExhaustedError" error:
`tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[24,10,10,960] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: FeatureExtractor/MobilenetV2/expanded_conv_16/depthwise/Relu6-1-1-TransposeNCHWToNHWC-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/MobilenetV2/expanded_conv_16/depthwise/Relu6, PermConstNCHWToNHWC-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: Loss/Where_79/_20629 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_26219_Loss/Where_79", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.`

I thought that mobilenet should be memory efficient, I have Titan X with 12GB and still.. I will play with data/batch sizes, maybe this will help. Did you come across this? I assume google cloud ML has unlimited resources so for them it's not a problem, but still..

**Comment by SnowRipple** [comment]
Hey @victorbonnet! Is there a relation between number of training steps and batch_size?

**Comment by victorbonnet** [comment]
One training step correspond to one batch to be processed.
Batch size represents the num of images to process at the same time.

You can calculate the number of steps for 1 epoch, steps = number of images / batch size

**Comment by SnowRipple** [comment]
Thanks! I have last question for you: what versions of sdk and ndk did you use? I installed the app on my phone but it closes the moment I open it.

**Comment by victorbonnet** [comment]
I am using ndk `android-ndk-r14b` and the sdk is `26.0.2`

Do you have a stacktrace ?

**Comment by SnowRipple** [comment]
Yes, so I used adb logcat and here is the stacktrace:

 <pre>09-03 11:57:42.816 31131 31147 E AndroidRuntime: FATAL EXCEPTION: inference
09-03 11:57:42.816 31131 31147 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 31131
09-03 11:57:42.816 31131 31147 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at java.util.Vector.get(Vector.java:748)
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:214)
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:247)
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-03 11:57:42.816 31131 31147 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-03 11:57:42.818  3457 13279 W ActivityManager:   Force finishing activity org.tensorflow.lite.demo/org.tensorflow.demo.DetectorActivity
09-03 11:57:42.820  3457 13279 V SignBoardCoverServiceDelegate: onCoverHide()
09-03 11:57:42.822  3457 13279 I WindowManager: focusedWin.mLastOrientation : 0
09-03 11:57:42.822  3457 13279 D InputDispatcher: Focus left window: Window{dbf637e u0 org.tensorflow.lite.demo/org.tensorflow.demo.DetectorActivity}
09-03 11:57:42.823  3457 13279 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
09-03 11:57:42.833  4986  7780 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:879 android.content.ContextWrapper.sendBroadcast:421 com.lge.mlt.providers.LDBSmartCareTrigger.sendMsgSmartCare:33 com.lge.mlt.providers.LDBMainLogProvider.insert:268 android.content.ContentProvider$Transport.insert:264 
09-03 11:57:42.839  3457  4101 W ActivityManager: Sending non-protected broadcast com.lge.mlt.action.smartcare.event from system 4986:com.lge.mlt/1000 pkg com.lge.mlt
09-03 11:57:42.849  3457  3497 D InputDispatcher: Focus entered window: Window{4dee9c7 u0 Application Error: org.tensorflow.lite.demo}</pre>

**Comment by SnowRipple** [comment]
Btw, what does "???\nwaldo" command does?

**Comment by victorbonnet** [comment]
This is the labels of object trained to be detected. The first one is already used by the model that's why we use `???`.

did you run this command?
```
${WALDO_REPO}/tensorflow/tensorflow/contrib/lite/examples/android/app/src/main/assets/waldo.txt
```

if so can you check in the assets folder, if `waldo.txt` exists and if the content is 
```
???
waldo
```

You could try to print `outputClasses[0][i]` in `TFLiteObjectDetectionAPIModel`. Your model should not return something bigger than 1. If so It might be because you use a wrong model, or it has been trained with more labels.

**Comment by SnowRipple** [comment]
Thanks for your suggestion! The problem was that the command
`echo "???\nwaldo" > filepath` 
treats \n as a string instead of newline character for some reason. It works now! Woohoo!!

Many Thanks for your assistance, you did amazing work, this is a great  project!
